### PR TITLE
HSM support for DE middleware

### PR DESCRIPTION
**Pull request by Razumain**
This PR includes a complete sample implementation use of the [PKCS#11 lib from Sweden Connect](https://github.com/swedenconnect/opensaml-pkcs11) to add HSM support to the DE middleware.

The intention is to provide as few changes as possible to the middleware code and configuration files. The only change to the original code is provided in the ConfigHolder class used to retrieve configured keys and certificates. If a PKCS#11 key is available, this is chosen instead of any configured jks/p12 keys.

Two new classes are added to import PKCS#11 configuration data and to setup the use of PKCS#11 credentials:

**EidasSignerPKCS11ConfigData** - Reads configuration data from a properties file. 
**EidsaSignerCredentialConfiguration** - Configures PKCS#11 credential based on the PKCS#11 properties data.

Two files are provided in the project root directory as example implementations:

- **Dockerfile-softhsm-eidasmiddleware** - This Dockerfile demonstrates how the middleware can be deployed in a docker container with SoftHSM and other necessary tools installed in order to test PKCS#11 without a real HSM.
- **pkcs11.properties** - This is a sample properties file used to setup SoftHSM test but can be modified to specify the use of real HSM.

Two environment variables are used to initiate use of the PKCS#11 configuration
- PKCS11_CONFIG_LOCATION - Specifies the location of the pkcs11 properties file.
- PKCS11_PIN - (Optional) overrides the PIN setting in the properties file to avoid storing the pin on hard drive.

### CODE REVIEW

**Comment by Razumain** [comment]
I just made an amendment to this PR where I separate the signing and encryption key.

The reason for this is caused by using ECDSA for signing as SunPKCS11 do not support RSASSA-PSS. According to the eIDAS specifications EC key is not supported for encryption.

The middleware application does not at this time use any private key for decryption purposes,  but a such key is published in metadata. It would then be clearly wrong to publish an EC key as encryption key.

The current example illustrates where one EC key is configured for signing while an RSA key is configured for encryption.

**Comment by Razumain** [comment]
We made an update to the PKCS#11 library in order to accommodate the API changes in java 9+.

There are backwards incompatible changes between Java 8 and Java 9+ which are accommodated in this update. I made the related updates to this PR to make use of the updated PKCS#11 lib.

**Comment by Razumain** [comment]
Recent attempts to make this work for Amazon cloud HSM may require a customised way to extract private key objects from providers as well as customised ways to create the provider. A new release 1.1.1 of the Java PCS#11 lib provides an interface for defining custom method for private key handler extraction from a registered provider.

Example implementation code in the EidsaSignerCredentialConfiguration class:

samlMessageSigningCredential = new PKCS11Credential(
        getCert(pkcs11Config.getKeySourceCertLocation()),
        pkcs11Provider.getProviderNameList(),
        pkcs11Config.getKeySourceAlias(),
        new CustomKeyExtractor() {
            @Override
            public PrivateKey getPrivateKey(String providerName, String alias) throws Exception {
                KeyStore keyStore = KeyStore.getInstance("PKCS11", providerName);
                keyStore.load(null, pkcs11Config.getKeySourcePass().toCharArray());
                return (PrivateKey) keyStore.getKey(alias, pkcs11Config.getKeySourcePass().toCharArray());
            }
        }
);

**Comment by bennypi** [comment]
HSM support is available since version 1.1.0. This PR will be closed.

**Pull request closed without merging**
