### PR TITLE
Bugfix version 1.0.5 - SAML Assertions

### PR DESCRIPTION
**Pull request by Razumain**
This PR corrects the current SAML bug in version 1.0.5 which also prevents the Middleware from working with the CEF implementation.

### CODE REVIEW

**Comment by vixus0** [comment]
I've also spotted this bug and it's currently blocking us from integrating the middleware with our connector. 
@Razumain you should make the same change in `fail_asso_tempalte.xml` I believe.

**Comment by Razumain** [comment]
@vixus0 
Hi Anshur

There is one important reason why we have not done the update to `fail_asso_tempalte.xml`.
Assertions SHALL NOT, as defined in the SAML standard, be included in error responses when authentication has not succeeded. In our modification to the DE middleware, we simply have removed the assertion from error responses. 

SAML 2.0 specifies in section 3.3.4:

"**_If the SAML authority cannot provide an assertion with any statements satisfying the constraints
expressed by a query or assertion reference, the element MUST NOT contain an
<Assertion> element_**"

**Comment by vixus0** [comment]
@Razumain You're right. Maybe the removal could be added to this PR?
@bennypi Any ideas on whether this will be merged?

**Comment by Razumain** [comment]
@vixus0 I included that update in en earlier PR [Updates 1.0.5 rc1](https://github.com/Governikus/eidas-middleware/pull/5). I got the impression that they didn't want that update, so I reduced this PR to just the serious SAML bug.

**Comment by vixus0** [comment]
@Razumain @bennypi In that case it's definitely worthwhile for that PR to get merged.

**Comment by hbruns** [comment]
Not yet applicable due to https://ec.europa.eu/cefdigital/tracker/browse/EID-630

**Comment by bennypi** [comment]
Closed because implemented with https://github.com/Governikus/eidas-middleware/releases/tag/1.0.6

**Pull request closed without merging**
